### PR TITLE
Superkeys development

### PR DESCRIPTION
**Pull request by AlexDygma**
Introduced a new Plugin called SuperKeys based on the Tapdance and DynamicTapdance plugins, which offers standard functionality and adds more personalization options.

Signed-off-by: alexpargon <alexpargon@gmail.com>

### CODE REVIEW

**Comment by GirlBossRush** [comment]
This looks really exciting! After switching from an ErgoDox, having a dual use shift/parenthesis key would be lovely.

**Comment by AlexDygma** [comment]
> This looks really exciting! After switching from an ErgoDox, having a dual use shift/parenthesis key would be lovely.

Hey @TeffenEllis ! it is! I hope you are enjoying the superkeys, we are starting to merge all the changes to the main branch so that anyone that wants to, can contribute! 

PS: sorry for the late response 😅

**Comment by GirlBossRush** [comment]
@AlexDygma,

Thank you for all the great work on this feature! I’ve been keeping track of the updates and it’s really coming together. It’s a bit of a kludge, but I was able to emulate this behavior by patching Bazecor’s numpad. AFAIK, there isn’t a dedicated keycode for parenthesis on *nix, so I started by adding a few dead keycodes:

#### **`numpad.js`**
```js
const NumpadTable = {
  groupName: "Numpad",
  keys: [
    {
      code: 180,
      labels: {
        top: "Numpad",
        primary: "180"
      }
    },
    {
      code: 181,
      labels: {
        top: "Numpad",
        primary: "181"
      }
    }
  ]
};
```

From there, I mapped the shift keys to 180 and 181, respectively. This solved half the issue (getting another key to trigger when a modifier is pressed without a primary key), but I still needed a way to a parenthesis to appear. I already use [Karabiner-Elements](https://karabiner-elements.pqrs.org), so this was as easy as adding a complex modifier:

#### **`karabiner.json`**
```jsonc
{
  // Config truncated...
  "profiles": [
    {
      "complex_modifications": {
        "parameters": {
          "basic.simultaneous_threshold_milliseconds": 50,
          "basic.to_delayed_action_delay_milliseconds": 500,
          "basic.to_if_alone_timeout_milliseconds": 1000,
          "basic.to_if_held_down_threshold_milliseconds": 500,
          "mouse_motion_to_scroll.speed": 100
        },
        "rules": [
          {
            "description": "Dygma Patch",
            "manipulators": [
              {
                "from": {
                  "key_code": 180,
                  "modifiers": {
                    "mandatory": [],
                    "optional": [
                      "any"
                    ]
                  }
                },
                "to": [
                  {
                    "key_code": 38,
                    "modifiers": [
                      "left_shift"
                    ]
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": 181,
                  "modifiers": {
                    "mandatory": [],
                    "optional": [
                      "any"
                    ]
                  }
                },
                "to": [
                  {
                    "key_code": 39,
                    "modifiers": [
                      "left_shift"
                    ]
                  }
                ],
                "type": "basic"
              }
            ]
          }
        ]
      }
    }
  ]
}
```

This has worked out well so far, albeit very fragile and limited, so I’m looking forward to trying out your version soon!

**Comment by AlexDygma** [comment]
Thanks for your support @TeffenEllis !

The SK will require still a bit of a rework, but I'm merging this branch as we will improve them after implementing more changes.

**Pull request merged**
